# Numpy For Machine Learning

## Section 1: Intro To Numpy

- Numperic python or Numpy is a special type of array in python.
- we use numpy when we have a massive amount of data
- numpy is just a python list with more power full features
- Data type (ndarray)

In [1]:
import numpy as np

In [3]:
a = np.array(5)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array(5)

### 0-Dim Array

In [42]:
np0 = np.array(5)

In [43]:
np0.shape

()

### 1-Dim Array

In [44]:
np1 = np.array([1,2,3,4,5])

In [45]:
np1

array([1, 2, 3, 4, 5])

In [46]:
np1[2]

np.int64(3)

In [47]:
np1.shape

(5,)

In [48]:
np1.size

5

In [49]:
np2=np.arange(10)

In [50]:
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np3=np.arange(0,100,10)

In [52]:
np3

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
np4 = np.zeros(5)

In [57]:
np4

array([0., 0., 0., 0., 0.])

### Multi-Dimentional Array

In [62]:
np5 = np.zeros((5,10))

In [63]:
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Full functions

In [90]:
np6 = np.full((3),5)

In [91]:
np6

array([5, 5, 5])

In [92]:
np6 = np.full((2,4),5)

In [93]:
np6

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [94]:
np6 = np.full((2,4,3),5)

In [95]:
np6

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

### Change list into numpy

In [96]:
my_list = [1,2,3,4,5]

In [97]:
np7 = np.array(my_list)

In [98]:
np7

array([1, 2, 3, 4, 5])

In [100]:
np7[2]

np.int64(3)

## SECTION 2: Slicing Numpy Arrays

In [101]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [102]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
np1[2:6]

array([3, 4, 5, 6])

In [105]:
np1[:6]

array([1, 2, 3, 4, 5, 6])

In [106]:
np1[5:]

array([ 6,  7,  8,  9, 10])

In [107]:
np1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [109]:
np1[-7:-1]

array([4, 5, 6, 7, 8, 9])

In [113]:
np1[1:9:2]

array([2, 4, 6, 8])

In [115]:
np1[::2]

array([1, 3, 5, 7, 9])

## Slicing 2-D Array

In [126]:
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [127]:
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [128]:
np2[0,4]

np.int64(5)

In [129]:
np2[1,2]

np.int64(8)

In [138]:
# [Rows, Columns]
np2[:1, 1:4]

array([[2, 3, 4]])

## Universal functions in numpy

In [147]:
u = np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [148]:
u

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [149]:
# Square root of each element
np.sqrt(u)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [150]:
# Absolute value
np.absolute(u)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [152]:
# Exponent of each number
np.exp(u)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [153]:
# Min or max

In [155]:
np.min(u)


np.int64(1)

In [156]:
np.max(u)

np.int64(10)

In [158]:
x = np.array([[1,-2,3,-4,5],[6,7,8,9,10]])


In [160]:
# find sign
np.sign(x)

array([[ 1, -1,  1, -1,  1],
       [ 1,  1,  1,  1,  1]])

In [161]:
# Log
np.log(u)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

## Copy vs View

**Copy**: Copy the array and make the new one
**View**: Copy the array but still connected with the original one

In [163]:
x = np.array([1,2,3,4,5])

In [178]:
# View
y = x.view()

In [179]:
y

array([ 1, 41, 90,  4,  5])

In [180]:
x[1]=41

In [181]:
y

array([ 1, 41, 90,  4,  5])

In [182]:
y[1]=40

In [183]:
x

array([ 1, 40, 90,  4,  5])

In [184]:
# Copy
y=x.copy()

In [185]:
y

array([ 1, 40, 90,  4,  5])

In [186]:
x[2]=90

In [187]:
x

array([ 1, 40, 90,  4,  5])

In [188]:
y

array([ 1, 40, 90,  4,  5])

## Shape and Reshape Numpy

In [199]:
# 1D array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [200]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [201]:
np1.shape

(12,)

In [202]:
# 2D Array
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [203]:
np2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [204]:
np2.shape

(2, 6)

In [205]:
# Reshape 1D to 2D

np3 = np1.reshape(3,4)

In [206]:
np3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [207]:
np3.shape

(3, 4)

In [208]:
np3.size

12

In [218]:
# 1D to 3D (Block - rows - Columns
np4 = np1.reshape(3,2,2)

In [219]:
np4

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [220]:
np4.shape

(3, 2, 2)

In [222]:
# Flatten to 1D
np5 = np4.reshape(-1)

In [223]:
np5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])