# Numpy For Machine Learning

## Section 1: Intro To Numpy

- Numperic python or Numpy is a special type of array in python.
- we use numpy when we have a massive amount of data
- numpy is just a python list with more power full features
- Data type (ndarray)

In [1]:
import numpy as np

In [3]:
a = np.array(5)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array(5)

### 0-Dim Array

In [42]:
np0 = np.array(5)

In [43]:
np0.shape

()

### 1-Dim Array

In [44]:
np1 = np.array([1,2,3,4,5])

In [45]:
np1

array([1, 2, 3, 4, 5])

In [46]:
np1[2]

np.int64(3)

In [47]:
np1.shape

(5,)

In [48]:
np1.size

5

In [49]:
np2=np.arange(10)

In [50]:
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np3=np.arange(0,100,10)

In [52]:
np3

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
np4 = np.zeros(5)

In [57]:
np4

array([0., 0., 0., 0., 0.])

### Multi-Dimentional Array

In [62]:
np5 = np.zeros((5,10))

In [63]:
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Full functions

In [90]:
np6 = np.full((3),5)

In [91]:
np6

array([5, 5, 5])

In [92]:
np6 = np.full((2,4),5)

In [93]:
np6

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [94]:
np6 = np.full((2,4,3),5)

In [95]:
np6

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

### Change list into numpy

In [96]:
my_list = [1,2,3,4,5]

In [97]:
np7 = np.array(my_list)

In [98]:
np7

array([1, 2, 3, 4, 5])