# Tensors
Tensors are the fundamental data structure used in machine learning and deep learning to store and manipulate data — essentially a generalization of numbers, vectors, and matrices into any number of dimensions.

**Core idea:** Think of tensors as a container for numerical data, where the "dimension" tells you how the data is structured:

## 0D Tensors / Scalars / 0D Array

In [1]:
import numpy as np

In [12]:
a = np.array(4)


In [13]:
# Scalar or 0 dimension array or tensor
a

array(4)

In [14]:
a.ndim

0

In [ ]:
## 1D tensors / Tensors / 1D array / Vectors

## If we add scalars we will get vectors

In [21]:
a = np.array([4,4,5,7,5])
a


array([4, 4, 5, 7, 5])

In [22]:
a.ndim

1

In [23]:
## No of axis = Rank = dimensions of tensors

# 2D tensors

when we have multiple vectors and when we add or collect them we will get a 2d Tensors. Matrics are nothing but a collection of vetors.

In [29]:
a = np.array([[4,4,5,7,5],[64,4,3,5,4]])
a

array([[ 4,  4,  5,  7,  5],
       [64,  4,  3,  5,  4]])

In [30]:
a.ndim

2

In [31]:
b = np.array([[4,4,5,7,5],[64,4,3,5,4],[34,35,6,4,6]])
b

array([[ 4,  4,  5,  7,  5],
       [64,  4,  3,  5,  4],
       [34, 35,  6,  4,  6]])

# nD tensors / 3D tensors
3D Tensors are tensors with three dimensions/axes — essentially a "stack" of multiple 2D matrices layered together.

**Core idea:** If a 2D tensor (matrix) is a single grid of rows and columns, a 3D tensor is multiple such grids stacked on top of each other — adding a third dimension, often called "depth" or "channels."

In [32]:
c = np.array([
    [[4,4,5,7,5],[64,4,3,5,4],[34,35,6,4,6]],
     [[4,4,5,7,5],[64,4,3,5,4],[34,35,6,4,6]],
     [[4,4,5,7,5],[64,4,3,5,4],[34,35,6,4,6]]
])
c

array([[[ 4,  4,  5,  7,  5],
        [64,  4,  3,  5,  4],
        [34, 35,  6,  4,  6]],

       [[ 4,  4,  5,  7,  5],
        [64,  4,  3,  5,  4],
        [34, 35,  6,  4,  6]],

       [[ 4,  4,  5,  7,  5],
        [64,  4,  3,  5,  4],
        [34, 35,  6,  4,  6]]])

In [34]:
c.ndim
c.shape

(3, 3, 5)

## 4D Tensors:
collectiob of 3d tensors

 # Rank = Axis = No of dims

size = shape = no of row x no of columns
